# Site wide configuration

title:            Sean Hagen.ca
locale:           en_US
url:

# Jekyll configuration

permalink:   /:year/:month/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

collections:
  projects:
    output: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

image:
  source: assets/images/_fullsize
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    half:
      width: 400
      height: 400

# Site owner
owner:
  name: Sean Patrick Hagen
  avatar: th_drkrug2.gif
  bio: "Just a Vancouver coder"
  email: sean.hagen@gmail.com
  disqus-shortname:
  twitter: seanhagen
  facebook: #username
  google:
    plus: SeanPatrickHagen
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: seanhagen
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: seanpatrickhagen
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: rebelcan
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
