baseURL: https://seanhagen.ca
disablePathToLower: true
languageCode: en-us
title: Sean Hagen.ca
theme: hugo-photo-theme

indexes:
  post: "posts"

permalinks:
  post: "/:year/:month/:title/"

params:
  author:
    name: "Sean Patrick Hagen"
    avatar: th_drkrug2.gif
    bio: Vancouver based programmer who also does stuff with D&D and video games.

    social:
      twitter: seanphagen
      youtube: UCtiOKGxaqjI7ZqTS2xtb97g
      twitch: seanphagen
      linkedin:

        # linkedin = ""
        # instagram = ""
        # tumblr = ""
        # github = ""
        # stackoverflow = ""
        # pinterest = ""
        # steam = ""
        # soundcloud = ""
        # flickr = ""
        # codepen = ""



  header:
    feature: "window-cropped"
    credit: "Sean Hagen"
    creditlink: "https://www.flickr.com/photos/rebelcan/12754943013/in/datetaken-public/"
